# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [
      <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "usb_storage" "sd_mod" "sr_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ "dm-snapshot" "coretemp" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];
  boot.kernelParams = [
    "acpi_backlight=vendor"
    "video.use_native_backlight=1"
    "intel_pstate=active"
  ];

  boot.initrd.luks.devices.root =
    {
      device = "/dev/disk/by-uuid/18b41806-9aff-4676-8672-919d79aad5a5";
      preLVM = true;
      allowDiscards = true;
    };
  fileSystems."/" =
    {
      device = "/dev/disk/by-uuid/7dab1198-09b9-4c72-b508-d859a1f3da02";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/6671-BF32";
      fsType = "vfat";
    };

  fileSystems."/data" =
    {
      device = "/dev/disk/by-label/DATA";
    };

  swapDevices =
    [{ device = "/dev/disk/by-uuid/8aa3d11b-4b84-44e1-bb88-c4f58440b2ee"; }];

  nix.maxJobs = lib.mkDefault 4;

  powerManagement.enable = true;
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  powerManagement.powertop.enable = true;
  hardware.bluetooth.enable = true;

  hardware.opengl.extraPackages = with pkgs; [ vaapiIntel libvdpau-va-gl vaapiVdpau intel-ocl ];

}
