[stable]
packages = [
    "wget",
    "vim",
    "joe",
    "mc",
    "lightdm",
    "parted",
    "firefox",
    "pciutils",
    "networkmanagerapplet",
    "findutils",
    "unzip",
    "htop",
    "hicolor_icon_theme",
    "inetutils",
    "ntfs3g",
    "iw",
    "wirelesstools",
    "iptables",
    "tunctl",
    "gtk_engines",
    "docker",
    "usbutils",
    "gitFull",
    "mtr",
    "gnumake",
    "python3",
    "gcc",
    "greybird",
    "rofi",
    "numix-gtk-theme",
    "xfce.xfce4-clipman-plugin",
    "xfce.xfce4-battery-plugin",
    "xfce.xfce4-systemload-plugin",
    "xfce.xfce4-sensors-plugin",
    "glances",
    "powertop",
    "xsensors",
    "lm_sensors",
    "xorg.xev",
    "light",
    "arandr",
    "elementary-xfce-icon-theme",
    "xsecurelock",
    "i3lock",
    "xorg.xhost",
    "spotify",
    "rhythmbox",
    "glmark2",
    "vlc",
    "jetbrains.pycharm-community",
    "xorg.xf86inputsynaptics",
    "binutils-unwrapped",
    "manpages",
    "dotnet-sdk",
    "bc",
    "gthumb",
    "gimp",
    "file",
    "lshw",
    "nix-diff",
    "nox",
    "libinput",
    "hdparm",
    "speedtest-cli",
    "dosbox",
    "rtorrent",
    "mplayer",
    "ffmpeg",
    "mediainfo",
    "google-chrome",
    "evince",
    "libreoffice",
    "hunspell",
    "nodejs",
    "yarn",
    "rclone",
    "pwgen",
    "iperf2",
    "lzop",
    "squashfsTools",
    "gptfdisk",
    "gitAndTools.gitFull",
    "pypy",
    "pypy3",
    "fping",
    "tcpdump",
    "sysstat",
    "nmon",
    "dpkg",
    "screen",
    "miniupnpc_2",
    "mcrypt",
    "p7zip",
    "dia",
    "unrar",
    "python310",
    "brightnessctl",
    "killall",
    "sqlite-interactive",
    "zip",
    "exif",
    "exiv2",
    "openssl",
    "patchelf",
    "ncat",
    "pre-commit",
    "direnv",
    "gnomecast",
    "mkvtoolnix",
    "bat",
    "bind",
    "smartmontools",
    "docker-compose",
    "kotlin",
    "ktlint",
    "adoptopenjdk-jre-bin",
    "byzanz",
    "clang-tools",
    "glibc.static",
    "gdb",
    "jq",
    "smbclient",
    "glxinfo",
    "ncdu",
    "cifs-utils",
    "flameshot",
    "ripgrep",
    "virt-manager",
    "nixpkgs-fmt",
    "pre-commit",
    "openttd-jgrpp",
    "python3Packages.ipython",
    "python3Packages.pylint",
    "python3Packages.black",
    "python3Packages.autopep8",
    "python3Packages.rope",
    "python3Packages.lxml",
    "python3Packages.setuptools",
    "python3Packages.tox",
    "python3Packages.pyglet",
    "python3Packages.future",
    "python3Packages.pytest",
    "python3Packages.pip",
    "python3Packages.pyopengl-accelerate",
    "python3Packages.bitarray",
    "kitty",
]

[unstable]
packages = [
    "vscode",
    "inkscape",
    "geeqie",
    "tesseract4",
    "arduino",
    "castnow",
    "poetry",
    "rustup",
    "rustc",
    "cargo",
    "restic",
    "kdenlive",
    "citrix_workspace",
]
