{ config, pkgs, ... }:

let
  unstable = import <nixos-unstable> { config = { allowUnfree = true; }; };
in
{
  # List packages installed in system profile. To search, run:
  # $ nix search wget
  environment.systemPackages = with pkgs; [
    wget
    vim
    joe
    mc
    lightdm
    parted
    firefox
    pciutils
    networkmanagerapplet
    findutils
    unzip
    htop
    hicolor_icon_theme
    inetutils
    ntfs3g
    iw
    wirelesstools
    iptables
    tunctl
    gtk_engines
    docker
    usbutils
    unstable.vscode
    gitFull
    mtr
    gnumake
    python3
    gcc
    unstable.kitty
    greybird
    rofi
    numix-gtk-theme
    xfce.xfce4-clipman-plugin
    xfce.xfce4-battery-plugin
    xfce.xfce4-systemload-plugin
    xfce.xfce4-sensors-plugin
    glances
    powertop
    xsensors
    lm_sensors
    xorg.xev
    light
    arandr
    elementary-xfce-icon-theme
    xsecurelock
    i3lock
    xorg.xhost
    spotify
    rhythmbox
    glmark2
    python3Packages.ipython
    python3Packages.pylint
    python3Packages.black
    python3Packages.autopep8
    python3Packages.rope
    python3Packages.lxml
    python3Packages.setuptools
    python3Packages.tox
    python3Packages.pyglet
    python3Packages.future
    python3Packages.pytest
    python3Packages.pip
    python3Packages.pyopengl-accelerate
    python3Packages.bitarray

    vlc
    jetbrains.pycharm-community
    xorg.xf86inputsynaptics
    binutils-unwrapped
    manpages
    dotnet-sdk
    bc
    unstable.inkscape
    unstable.geeqie
    gthumb
    gimp
    file
    lshw
    nix-diff
    nox
    libinput
    hdparm
    speedtest-cli
    dosbox
    rtorrent
    mplayer
    ffmpeg
    mediainfo
    google-chrome
    # mate.atril
    evince
    libreoffice
    hunspell
    nodejs
    yarn
    rclone
    pwgen
    iperf2
    lzop
    squashfsTools
    gptfdisk
    gitAndTools.gitFull
    # kicad
    pypy
    pypy3
    fping
    tcpdump
    sysstat
    nmon
    unstable.tesseract4
    # unstable.imagemagick
    dpkg
    screen
    miniupnpc_2
    mcrypt
    p7zip
    dia
    unrar
    python310
    brightnessctl
    killall
    sqlite-interactive
    zip
    exif
    exiv2
    openssl
    unstable.arduino
    # unstable.platformio
    patchelf
    ncat
    pre-commit
    direnv
    gnomecast
    unstable.castnow
    mkvtoolnix
    unstable.poetry
    bat
    bind
    smartmontools
    docker-compose
    unstable.rustup
    unstable.rustc
    unstable.cargo
    kotlin
    ktlint
    adoptopenjdk-jre-bin
    byzanz
    clang-tools
    glibc.static
    gdb
    jq
    #    processing
    smbclient
    unstable.restic
    glxinfo
    unstable.kdenlive
    ncdu
    #    typora
    cifs-utils
    flameshot
    ripgrep
    virt-manager
    nixpkgs-fmt
    pre-commit
    openttd-jgrpp
  ];


}
